using System.Collections.Generic;
using System.Linq;

namespace TeachFlex.Services
{
    public static class BowSourceCatalog
    {
        private static readonly (string Grade, string File)[] Entries =
        {
            ("Grade 1", "[G1] GMRC.pdf"),
            ("Grade 1", "[G1] Language.pdf"),
            ("Grade 1", "[G1] MAKABANSA.pdf"),
            ("Grade 1", "[G1] Mathematics.pdf"),
            ("Grade 1", "[G1] Reading and Literacy.pdf"),
            ("Grade 10", "[G10] Araling Panlipunan.pdf"),
            ("Grade 10", "[G10] English.pdf"),
            ("Grade 10", "[G10] Filipino.pdf"),
            ("Grade 10", "[G10] MAPEH.pdf"),
            ("Grade 10", "[G10] Mathematics.pdf"),
            ("Grade 10", "[G10] Science.pdf"),
            ("Grade 10", "[G10] Values Education.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ AFA - Agricultural Crop Production.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ AFA - Animal Production.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ AFA - Aquaculture (Fish Culture).pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ AFA - Fish Capture.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ AFA - Food and Beverage Processing.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Beauty Care Services.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Food Preparation .pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Food Service.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Garments.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Handicraft.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Health and Wellness Massage.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Hotel Services.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ FCS - Tourism Services.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ IA - Automotive and Small Engine Servicing.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ IA - Electrical and Electronics Servicing.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ IA - Residential Carpentry.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ IA - Residential Masonry and Tile Setting.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ IA - Residential Plumbing.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ IA - Shielded Metal Arc Welding (SMAW).pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ ICT - Computer Programming.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ ICT - Computer Systems Servicing.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ ICT - Telecommunications.pdf"),
            ("Grade 10", "[G9 _ G10] TLE_ ICT - Visual Arts.pdf"),
            ("Grade 11", "Advanced Mathematics.pdf"),
            ("Grade 11", "Art Criticism and Creative Markets (New).pdf"),
            ("Grade 11", "Arts Apprenticeship - Literary Arts.pdf"),
            ("Grade 11", "Arts Apprenticeship - Media Arts.pdf"),
            ("Grade 11", "Arts Apprenticeship – Dance.pdf"),
            ("Grade 11", "Arts Apprenticeship – Music .pdf"),
            ("Grade 11", "Arts Apprenticeship – Theater Arts .pdf"),
            ("Grade 11", "Arts Apprenticeship – Traditional Cultural Expressions .pdf"),
            ("Grade 11", "Arts Apprenticeship – Visual Arts.pdf"),
            ("Grade 11", "Basic Calculus.pdf"),
            ("Grade 11", "Biology 1.pdf"),
            ("Grade 11", "Biology 2.pdf"),
            ("Grade 11", "Biology 3.pdf"),
            ("Grade 11", "Biology 4.pdf"),
            ("Grade 11", "Business 1 (Basic Accounting).pdf"),
            ("Grade 11", "Business 2 (Business Finance and Income Taxation).pdf"),
            ("Grade 11", "Business 3 (Business Economics).pdf"),
            ("Grade 11", "Chemistry 1.pdf"),
            ("Grade 11", "Chemistry 2.pdf"),
            ("Grade 11", "Chemistry 3.pdf"),
            ("Grade 11", "Chemistry 4.pdf"),
            ("Grade 11", "Citizenship and Civic Engagement.pdf"),
            ("Grade 11", "Conceptual Biology and Earth and Space Science.pdf"),
            ("Grade 11", "Conceptual Physics and Chemistry in Daily Life.pdf"),
            ("Grade 11", "Contemporary Literature 1.pdf"),
            ("Grade 11", "Contemporary Literature 2.pdf"),
            ("Grade 11", "Contemporary Marketing.pdf"),
            ("Grade 11", "Creative Composition1.pdf"),
            ("Grade 11", "Creative Composition2.pdf"),
            ("Grade 11", "Creative Industries - Applied and Traditional Arts (New).pdf"),
            ("Grade 11", "Creative Industries - Dance (New).pdf"),
            ("Grade 11", "Creative Industries - Literary Arts (New).pdf"),
            ("Grade 11", "Creative Industries - Music (New).pdf"),
            ("Grade 11", "Creative Industries - Theater Arts (New).pdf"),
            ("Grade 11", "Creative Industries - Visual Arts (New).pdf"),
            ("Grade 11", "Creative Production and Presentation.pdf"),
            ("Grade 11", "Database Management.pdf"),
            ("Grade 11", "Design and Innovation.pdf"),
            ("Grade 11", "Earth and Space Science 1.pdf"),
            ("Grade 11", "Earth and Space Science 2.pdf"),
            ("Grade 11", "Earth and Space Science 3.pdf"),
            ("Grade 11", "Earth and Space Science 4.pdf"),
            ("Grade 11", "Empowerment Technologies.pdf"),
            ("Grade 11", "Entrepreneurship.pdf"),
            ("Grade 11", "Exercise and Sports Programming.pdf"),
            ("Grade 11", "Filipino 1 (Wika at Komunikasyon sa Akademikong Filipino).pdf"),
            ("Grade 11", "Filipino 2 (Filipino sa Isports).pdf"),
            ("Grade 11", "Filipino 2 (Filipino sa Larang Teknikal-Propesyonal).pdf"),
            ("Grade 11", "Filipino 2 (Filipino sa Sining at Disenyo).pdf"),
            ("Grade 11", "Filipino Identity Through the Arts.pdf"),
            ("Grade 11", "Finite Mathematics 1.pdf"),
            ("Grade 11", "Finite Mathematics 2.pdf"),
            ("Grade 11", "First Aid.pdf"),
            ("Grade 11", "Fundamentals of Basic Life Support.pdf"),
            ("Grade 11", "Fundamentals of Data Analytics.pdf"),
            ("Grade 11", "Human Movement 1 (Basic Anatomy in Sports and Exercise).pdf"),
            ("Grade 11", "Human Movement 2 (Motor Skills Development).pdf"),
            ("Grade 11", "In-Campus Field Exposure for Sports.pdf"),
            ("Grade 11", "Introduction to Organization and Management.pdf"),
            ("Grade 11", "Introduction to the Philosophy of Human Person.pdf"),
            ("Grade 11", "Leadership and Management in the Arts.pdf"),
            ("Grade 11", "Malikhaing Pagsulat.pdf"),
            ("Grade 11", "Philippine Governance (Philippine Politics and Governance).pdf"),
            ("Grade 11", "Physical Education 1 (Fitness and Recreation).pdf"),
            ("Grade 11", "Physics 1.pdf"),
            ("Grade 11", "Physics 2.pdf"),
            ("Grade 11", "Physics 3.pdf"),
            ("Grade 11", "Physics 4.pdf"),
            ("Grade 11", "Pre-Calculus.pdf"),
            ("Grade 11", "Research 1.pdf"),
            ("Grade 11", "Research 2.pdf"),
            ("Grade 11", "Social Sciences (Theory and Practice).pdf"),
            ("Grade 11", "Sports Activity Management.pdf"),
            ("Grade 11", "Sports Coaching.pdf"),
            ("Grade 11", "Sports Officiating.pdf"),
            ("Grade 12", "G12-Aesthetic-Services-Beauty-Care.pdf"),
            ("Grade 12", "G12-Animation.pdf"),
            ("Grade 12", "G12-Bakery-Operations.pdf"),
            ("Grade 12", "G12-Caregiving-Adult-Care.pdf"),
            ("Grade 12", "G12-Caregiving-Child-Care.pdf"),
            ("Grade 12", "G12-Carpentry.pdf"),
            ("Grade 12", "G12-Computer-Programming-.Net-Technology.pdf"),
            ("Grade 12", "G12-Computer-Programming-Java.pdf"),
            ("Grade 12", "G12-Computer-Programming-Oracle-Database.pdf"),
            ("Grade 12", "G12-Computer-Systems-Servicing.pdf"),
            ("Grade 12", "G12-Construction Operation.pdf"),
            ("Grade 12", "G12-Contact-Center-Services.pdf"),
            ("Grade 12", "G12-Domestic-Refrigeration-and-Air-Conditioning-Servicing.pdf"),
            ("Grade 12", "G12-Driving-and-Automotive-Servicing.pdf"),
            ("Grade 12", "G12-Electrical-Installation-and-Maintenance.pdf"),
            ("Grade 12", "G12-Electronic-Products-Assembly-and-Servicing.pdf"),
            ("Grade 12", "G12-Events-Management-Services.pdf"),
            ("Grade 12", "G12-Food-and-Beverage-Operation.pdf"),
            ("Grade 12", "G12-Garments-Artisanry.pdf"),
            ("Grade 12", "G12-Hairdressing-Services.pdf"),
            ("Grade 12", "G12-Handicrafts_-Weaving.pdf"),
            ("Grade 12", "G12-Hotel-Operations-Front-Office-Services.pdf"),
            ("Grade 12", "G12-Hotel-Operations-Housekeeping-Services.pdf"),
            ("Grade 12", "G12-Illustration.pdf"),
            ("Grade 12", "G12-Kitchen-Operations.pdf"),
            ("Grade 12", "G12-Manual-Metal-Arc-Welding.pdf"),
            ("Grade 12", "G12-Maritime-Engineering-at-the-Support-Level.pdf"),
            ("Grade 12", "G12-Maritime-Transportation-at-the-Support-Level.pdf"),
            ("Grade 12", "G12-Motorcycle-and-Small-Engine-Servicing.pdf"),
            ("Grade 12", "G12-Photovoltaic-Systems-Installation.pdf"),
            ("Grade 12", "G12-Ships-Catering-Services.pdf"),
            ("Grade 12", "G12-Technical-Drafting.pdf"),
            ("Grade 12", "G12-Tourism-Services.pdf"),
            ("Grade 12", "G12-Visual-Graphic-Design.pdf"),
            ("Grade 2", "[G2] English.pdf"),
            ("Grade 2", "[G2] Filipino.pdf"),
            ("Grade 2", "[G2] GMRC.pdf"),
            ("Grade 2", "[G2] MAKABANSA.pdf"),
            ("Grade 2", "[G2] Mathematics.pdf"),
            ("Grade 3", "[G3] English.pdf"),
            ("Grade 3", "[G3] Filipino.pdf"),
            ("Grade 3", "[G3] GMRC.pdf"),
            ("Grade 3", "[G3] MAKABANSA.pdf"),
            ("Grade 3", "[G3] Mathematics.pdf"),
            ("Grade 3", "[G3] Science.pdf"),
            ("Grade 4", "[G4] Araling Panlipunan.pdf"),
            ("Grade 4", "[G4] English.pdf"),
            ("Grade 4", "[G4] EPP_ AFA _ FCS _ IA.pdf"),
            ("Grade 4", "[G4] EPP_ ICT.pdf"),
            ("Grade 4", "[G4] Filipino.pdf"),
            ("Grade 4", "[G4] GMRC.pdf"),
            ("Grade 4", "[G4] MAPEH.pdf"),
            ("Grade 4", "[G4] Mathematics.pdf"),
            ("Grade 4", "[G4] Science.pdf"),
            ("Grade 5", "[G5] Araling Panlipunan.pdf"),
            ("Grade 5", "[G5] English.pdf"),
            ("Grade 5", "[G5] EPP_ AFA _ FCS _ IA.pdf"),
            ("Grade 5", "[G5] EPP_ ICT.pdf"),
            ("Grade 5", "[G5] Filipino.pdf"),
            ("Grade 5", "[G5] GMRC.pdf"),
            ("Grade 5", "[G5] MAPEH.pdf"),
            ("Grade 5", "[G5] Mathematics.pdf"),
            ("Grade 5", "[G5] Science.pdf"),
            ("Grade 6", "[G6] Araling Panlipunan.pdf"),
            ("Grade 6", "[G6] English.pdf"),
            ("Grade 6", "[G6] Filipino.pdf"),
            ("Grade 6", "[G6] GMRC.pdf"),
            ("Grade 6", "[G6] MAPEH.pdf"),
            ("Grade 6", "[G6] Mathematics.pdf"),
            ("Grade 6", "[G6] Science.pdf"),
            ("Grade 6", "[G6] TLE_ AFA _ FCS _ IA.pdf"),
            ("Grade 6", "[G6] TLE_ ICT.pdf"),
            ("Grade 7", "[G7] Araling Panlipunan.pdf"),
            ("Grade 7", "[G7] English.pdf"),
            ("Grade 7", "[G7] Filipino.pdf"),
            ("Grade 7", "[G7] MAPEH.pdf"),
            ("Grade 7", "[G7] Mathematics.pdf"),
            ("Grade 7", "[G7] Science.pdf"),
            ("Grade 7", "[G7] TLE_ AFA _ FCS _ IA.pdf"),
            ("Grade 7", "[G7] TLE_ ICT.pdf"),
            ("Grade 7", "[G7] Values Education.pdf"),
            ("Grade 8", "[G8] Araling Panlipunan.pdf"),
            ("Grade 8", "[G8] English.pdf"),
            ("Grade 8", "[G8] Filipino.pdf"),
            ("Grade 8", "[G8] MAPEH.pdf"),
            ("Grade 8", "[G8] Mathematics.pdf"),
            ("Grade 8", "[G8] Science.pdf"),
            ("Grade 8", "[G8] TLE_ AFA _ FCS _ IA.pdf"),
            ("Grade 8", "[G8] TLE_ ICT.pdf"),
            ("Grade 8", "[G8] Values Education.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ AFA - Agricultural Crop Production.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ AFA - Animal Production.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ AFA - Aquaculture (Fish Culture).pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ AFA - Fish Capture.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ AFA - Food and Beverage Processing.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Beauty Care Services.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Food Preparation .pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Food Service.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Garments.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Handicraft.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Health and Wellness Massage.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Hotel Services.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ FCS - Tourism Services.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ IA - Automotive and Small Engine Servicing.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ IA - Electrical and Electronics Servicing.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ IA - Residential Carpentry.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ IA - Residential Masonry and Tile Setting.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ IA - Residential Plumbing.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ IA - Shielded Metal Arc Welding (SMAW).pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ ICT - Computer Programming.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ ICT - Computer Systems Servicing.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ ICT - Telecommunications.pdf"),
            ("Grade 9", "[G9 _ G10] TLE_ ICT - Visual Arts.pdf"),
            ("Grade 9", "[G9] Araling Panlipunan.pdf"),
            ("Grade 9", "[G9] English.pdf"),
            ("Grade 9", "[G9] Filipino.pdf"),
            ("Grade 9", "[G9] MAPEH.pdf"),
            ("Grade 9", "[G9] Mathematics.pdf"),
            ("Grade 9", "[G9] Science.pdf"),
            ("Grade 9", "[G9] Values Education.pdf"),
            ("Kindergarten", "Kindergarten BOW.pdf"),
            ("Kindergarten", "Kindergarten Learning Delivery Guide.pdf"),
        };
        public static IEnumerable<string> ForGrade(string grade) => Entries
            .Where(entry => string.Equals(entry.Grade, grade, System.StringComparison.OrdinalIgnoreCase))
            .Select(entry => entry.File);
    }
}
