using System;
using System.Collections.Generic;
using TeachFlex.Models;

namespace TeachFlex.Services
{
    public interface IGradeOnePaceCatalogService
    {
        IReadOnlyList<PaceCompetency> CreateOfficialCompetencies(
            int subjectId,
            string subjectName);
    }

    public class GradeOnePaceCatalogService :
        IGradeOnePaceCatalogService
    {
        public IReadOnlyList<PaceCompetency> CreateOfficialCompetencies(
            int subjectId,
            string subjectName)
        {
            string learningArea = NormalizeLearningArea(subjectName);
            List<PaceCompetency> competencies = new List<PaceCompetency>();
            int displayOrder = 1;
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonological Awareness (oracy for literacy)", "1", @"Chant rhymes and poems.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonological Awareness (oracy for literacy)", "2", @"Segment a two or three syllable word into its syllabic parts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonological Awareness (oracy for literacy)", "3", @"Identify rhyming words in nursery rhymes, poems, and chants.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonological Awareness (oracy for literacy)", "4", @"Say two or three words that rhyme.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonological Awareness (oracy for literacy)", "5", @"Identify initial sounds ((vowels, consonants, and semi-vowels, if any.)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonics and Word Study (sounds to words)", "6", @"Produce the sound of letters of L1.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Phonics and Word Study (sounds to words)", "6", @"Produce the sound of letters of L1.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Phonics and Word Study (sounds to words)", "6", @"Produce the sound of letters of L1.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonics and Word Study (sounds to words)", "7", @"Identify the letters in L1.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Phonics and Word Study (sounds to words)", "7", @"Identify the letters in L1.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Phonics and Word Study (sounds to words)", "7", @"Identify the letters in L1.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonics and Word Study (sounds to words)", "8", @"Isolate sounda (consonants and vowels) in a word (beginning and/or ending).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Phonics and Word Study (sounds to words)", "8", @"Isolate sounda (consonants and vowels) in a word (beginning and/or ending).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Phonics and Word Study (sounds to words)", "8", @"Isolate sounda (consonants and vowels) in a word (beginning and/or ending).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonics and Word Study (sounds to words)", "9", @"Substitute individual sounds in simple words to make new words.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Phonics and Word Study (sounds to words)", "9", @"Substitute individual sounds in simple words to make new words.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Phonics and Word Study (sounds to words)", "9", @"Substitute individual sounds in simple words to make new words.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Phonics and Word Study (sounds to words)", "10", @"Sound out words accurately.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Phonics and Word Study (sounds to words)", "10", @"Sound out words accurately.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Phonics and Word Study (sounds to words)", "10", @"Sound out words accurately.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Vocabulary and Word Knowledge (words)", "11", @"Use vocabulary referring to self, family, school, community, and environment.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Vocabulary and Word Knowledge (words)", "11", @"Use vocabulary referring to self, family, school, community, and environment.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Vocabulary and Word Knowledge (words)", "11", @"Use vocabulary referring to self, family, school, community, and environment.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Vocabulary and Word Knowledge (words)", "12a", @"a. words that label persons, places, things, animals, actions, situations, ideas, and emotions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Vocabulary and Word Knowledge (words)", "12a", @"a. words that label persons, places, things, animals, actions, situations, ideas, and emotions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Vocabulary and Word Knowledge (words)", "12a", @"a. words that label persons, places, things, animals, actions, situations, ideas, and emotions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Vocabulary and Word Knowledge (words)", "12b", @"b. words that describe persons, places, things, animals, actions, situations, ideas, and emotions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Vocabulary and Word Knowledge (words)", "12b", @"b. words that describe persons, places, things, animals, actions, situations, ideas, and emotions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Vocabulary and Word Knowledge (words)", "12b", @"b. words that describe persons, places, things, animals, actions, situations, ideas, and emotions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Vocabulary and Word Knowledge (words)", "13", @"Read high-frequency words accurately for meaning.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Vocabulary and Word Knowledge (words)", "13", @"Read high-frequency words accurately for meaning.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Vocabulary and Word Knowledge (words)", "13", @"Read high-frequency words accurately for meaning.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Vocabulary and Word Knowledge (words)", "14", @"Read content-specific words (Math, Makabansa, and GMRC) accurately for meaning.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Vocabulary and Word Knowledge (words)", "14", @"Read content-specific words (Math, Makabansa, and GMRC) accurately for meaning.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Vocabulary and Word Knowledge (words)", "14", @"Read content-specific words (Math, Makabansa, and GMRC) accurately for meaning.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Vocabulary and Word Knowledge (words)", "15", @"Write words legibly and correctly.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Vocabulary and Word Knowledge (words)", "15", @"Write words legibly and correctly.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Vocabulary and Word Knowledge (words)", "15", @"Write words legibly and correctly.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Book and Print Knowledge (words)", "16", @"Recognize environmental print (symbols).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Book and Print Knowledge (words)", "16", @"Recognize environmental print (symbols).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Book and Print Knowledge (words)", "16", @"Recognize environmental print (symbols).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Book and Print Knowledge (words)", "17", @"Recognize the parts of the book (cover page, title page, etc.).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Book and Print Knowledge (words)", "17", @"Recognize the parts of the book (cover page, title page, etc.).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Book and Print Knowledge (words)", "17", @"Recognize the parts of the book (cover page, title page, etc.).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Book and Print Knowledge (words)", "18", @"Recognize proper eye movement skills in reading: left to right, top to bottom, and return sweep.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Book and Print Knowledge (words)", "18", @"Recognize proper eye movement skills in reading: left to right, top to bottom, and return sweep.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Book and Print Knowledge (words)", "18", @"Recognize proper eye movement skills in reading: left to right, top to bottom, and return sweep.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "19", @"Read sentences with appropriate speed, accuracy, and expression.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Comprehending and Analyzing Texts (discourse)", "20a", @"a. Note important details in stories (character, setting, and events).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "20a", @"a. Note important details in stories (character, setting, and events).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "20a", @"a. Note important details in stories (character, setting, and events).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Comprehending and Analyzing Texts (discourse)", "20b", @"b. Sequence events in stories.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "20b", @"b. Sequence events in stories.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "20b", @"b. Sequence events in stories.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Comprehending and Analyzing Texts (discourse)", "20c", @"c. Infer the character's feelings and traits.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "20c", @"c. Infer the character's feelings and traits.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "20c", @"c. Infer the character's feelings and traits.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Comprehending and Analyzing Texts (discourse)", "20d", @"d. Predict possible ending.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "20d", @"d. Predict possible ending.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "20d", @"d. Predict possible ending.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Comprehending and Analyzing Texts (discourse)", "20e", @"e. Relate story events to one's experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "20e", @"e. Relate story events to one's experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "20e", @"e. Relate story events to one's experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "20f", @"f. Identify cause and effects of events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "20f", @"f. Identify cause and effects of events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "20g", @"g. Identify problem and solution in stories.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Comprehending and Analyzing Texts (discourse)", "21a", @"a. Note significant details in informational texts (list and describe).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "21a", @"a. Note significant details in informational texts (list and describe).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "21a", @"a. Note significant details in informational texts (list and describe).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Comprehending and Analyzing Texts (discourse)", "21b", @"b. Identify problem and solution.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Comprehending and Analyzing Texts (discourse)", "21b", @"b. Identify problem and solution.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Comprehending and Analyzing Texts (discourse)", "21b", @"b. Identify problem and solution.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "22", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "22", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "22", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "22b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "22b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "22b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "22c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "22c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "22c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "23", @"Use own words in retelling myths, legends, fables, and narrative poems.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "23", @"Use own words in retelling myths, legends, fables, and narrative poems.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "23", @"Use own words in retelling myths, legends, fables, and narrative poems.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "24a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "24a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "24a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "24b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "24b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "24b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "24c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "24c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "24c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 1, "Narrate one's personal experiences.", "25", @"Respond creatively to texts (myths, legends, fables, and narrative poems).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 2, "Narrate one's personal experiences.", "25", @"Respond creatively to texts (myths, legends, fables, and narrative poems).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Reading & Literacy", 3, "Narrate one's personal experiences.", "25", @"Respond creatively to texts (myths, legends, fables, and narrative poems).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "1a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "1a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "1b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "1c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "2a", @"a. Respond to teacher’s instructions.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "2a", @"a. Respond to teacher’s instructions.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "2a", @"a. Respond to teacher’s instructions.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "2b", @"b. Ask and respond to questions.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "2b", @"b. Ask and respond to questions.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "2b", @"b. Ask and respond to questions.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "3a", @"a. Make requests.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "3a", @"a. Make requests.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "3a", @"a. Make requests.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "3b", @"b. Offer information.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "3b", @"b. Offer information.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "3b", @"b. Offer information.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "3c", @"c. Communicate needs.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "3c", @"c. Communicate needs.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "3c", @"c. Communicate needs.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "3d", @"d. Clarify information.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "3d", @"d. Clarify information.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "3d", @"d. Clarify information.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "3e", @"e. Seek help.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "3e", @"e. Seek help.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "3e", @"e. Seek help.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "3f", @"f. Take part in or take turns in conversation or discussion.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "3f", @"f. Take part in or take turns in conversation or discussion.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "3f", @"f. Take part in or take turns in conversation or discussion.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "4a", @"a. Use simple and appropriate personal greetings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "4a", @"a. Use simple and appropriate personal greetings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "4a", @"a. Use simple and appropriate personal greetings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "4b", @"b. Use familiar terms of address.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "4b", @"b. Use familiar terms of address.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "4b", @"b. Use familiar terms of address.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "4c", @"c. Greet and respond appropriately to greetings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "4c", @"c. Greet and respond appropriately to greetings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "4c", @"c. Greet and respond appropriately to greetings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Interacting with Others", "5", @"Share confidently thoughts, preferences, needs, feelings, and ideas with peers, teachers, and other adults.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Interacting with Others", "5", @"Share confidently thoughts, preferences, needs, feelings, and ideas with peers, teachers, and other adults.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Interacting with Others", "5", @"Share confidently thoughts, preferences, needs, feelings, and ideas with peers, teachers, and other adults.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "6a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "6a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "6b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "6c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "7a", @"a. words that represent people, animals and objects, locations (naming words).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "7a", @"a. words that represent people, animals and objects, locations (naming words).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "7a", @"a. words that represent people, animals and objects, locations (naming words).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "7b", @"b. words that represent activities and situations (action words)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "7b", @"b. words that represent activities and situations (action words)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "7b", @"b. words that represent activities and situations (action words)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "7c", @"c. words that represent qualities or attributes (describing words)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "7c", @"c. words that represent qualities or attributes (describing words)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "7c", @"c. words that represent qualities or attributes (describing words)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "8a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "8a", @"a. oneself and family", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "8b", @"b. school", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "8c", @"c. community", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "9a", @"a. Express compare and contrast.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "9a", @"a. Express compare and contrast.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "9a", @"a. Express compare and contrast.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "9b", @"b. Express cause and effect.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "9b", @"b. Express cause and effect.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "9b", @"b. Express cause and effect.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "9c", @"c. Use time words to relate ideas.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "9c", @"c. Use time words to relate ideas.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "9c", @"c. Use time words to relate ideas.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "General", "10", @"Participate in and contribute to group oral language activities (e.g., singing, chanting, sabayang bigkas).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "General", "10", @"Participate in and contribute to group oral language activities (e.g., singing, chanting, sabayang bigkas).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "General", "10", @"Participate in and contribute to group oral language activities (e.g., singing, chanting, sabayang bigkas).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "11", @"Notice the features (e.g., sounds, intonation, signs) of their first language and other languages in familiar contexts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "11", @"Notice the features (e.g., sounds, intonation, signs) of their first language and other languages in familiar contexts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "11", @"Notice the features (e.g., sounds, intonation, signs) of their first language and other languages in familiar contexts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "12a", @"a. Recognize the difference between statements, questions, commands and exclamations.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "12a", @"a. Recognize the difference between statements, questions, commands and exclamations.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "12a", @"a. Recognize the difference between statements, questions, commands and exclamations.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "12b", @"b. Respond to change of tones and cues through facial expressions, gestures and actions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "12b", @"b. Respond to change of tones and cues through facial expressions, gestures and actions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "12b", @"b. Respond to change of tones and cues through facial expressions, gestures and actions", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "13a", @"a. Share about the language(s) spoken at home.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "13a", @"a. Share about the language(s) spoken at home.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "13a", @"a. Share about the language(s) spoken at home.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "13b", @"b. Share words and phrases in their language.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "13b", @"b. Share words and phrases in their language.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "13b", @"b. Share words and phrases in their language.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "13c", @"c. Notice how local names of streets, places and landmarks have origins in their language.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "13c", @"c. Notice how local names of streets, places and landmarks have origins in their language.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "13c", @"c. Notice how local names of streets, places and landmarks have origins in their language.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Language for Developing and Expressing Ideas", "13d", @"d. Explore local terms for food and their origins.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Language for Developing and Expressing Ideas", "13d", @"d. Explore local terms for food and their origins.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Language for Developing and Expressing Ideas", "13d", @"d. Explore local terms for food and their origins.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Interacting with Texts", "14", @"View and listen to a range of texts for enjoyment and interest.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Interacting with Texts", "14", @"View and listen to a range of texts for enjoyment and interest.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Interacting with Texts", "14", @"View and listen to a range of texts for enjoyment and interest.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Interacting with Texts", "15", @"Recognize icons and symbols in various texts found in familiar contexts (e.g., printed and digital texts, books, magazines, environmental print).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Interacting with Texts", "15", @"Recognize icons and symbols in various texts found in familiar contexts (e.g., printed and digital texts, books, magazines, environmental print).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Interacting with Texts", "15", @"Recognize icons and symbols in various texts found in familiar contexts (e.g., printed and digital texts, books, magazines, environmental print).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Interacting with Texts", "16a", @"a. View or listen to spoken texts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Interacting with Texts", "16a", @"a. View or listen to spoken texts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Interacting with Texts", "16a", @"a. View or listen to spoken texts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Interacting with Texts", "16b", @"b. Identify a variety of purposes for viewing and listening to texts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Interacting with Texts", "16b", @"b. Identify a variety of purposes for viewing and listening to texts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Interacting with Texts", "16b", @"b. Identify a variety of purposes for viewing and listening to texts.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Interacting with Texts", "16c", @"c. Discuss what is interesting or entertaining in a text.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Interacting with Texts", "16c", @"c. Discuss what is interesting or entertaining in a text.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Interacting with Texts", "16c", @"c. Discuss what is interesting or entertaining in a text.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Interacting with Texts", "16d", @"d. Express personal preferences.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Interacting with Texts", "16d", @"d. Express personal preferences.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Interacting with Texts", "16d", @"d. Express personal preferences.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Interacting with Texts", "17", @"Give reason/s for choosing books/texts for enjoyment and interest.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Interacting with Texts", "17", @"Give reason/s for choosing books/texts for enjoyment and interest.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Interacting with Texts", "17", @"Give reason/s for choosing books/texts for enjoyment and interest.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "18a", @"a. Note and report main points.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "18a", @"a. Note and report main points.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "18a", @"a. Note and report main points.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "18b", @"b. Sequence up to key three (3) key events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "18b", @"b. Sequence up to key three (3) key events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "18b", @"b. Sequence up to key three (3) key events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "18c", @"c. Relate ideas or events to one’s experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "18c", @"c. Relate ideas or events to one’s experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "18c", @"c. Relate ideas or events to one’s experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "19", @"Use own words in retelling information from various texts (e.g., legends, fables, and jokes).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "19", @"Use own words in retelling information from various texts (e.g., legends, fables, and jokes).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "19", @"Use own words in retelling information from various texts (e.g., legends, fables, and jokes).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "20a", @"a. Note and describe main points (e.g., main characters and events).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "20a", @"a. Note and describe main points (e.g., main characters and events).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "20a", @"a. Note and describe main points (e.g., main characters and events).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "20b", @"b. Sequence up to key three (3) key events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "20b", @"b. Sequence up to key three (3) key events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "20b", @"b. Sequence up to key three (3) key events.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "20c", @"c. Infer the character’s feelings and traits.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "20c", @"c. Infer the character’s feelings and traits.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "20c", @"c. Infer the character’s feelings and traits.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "20d", @"d. Predict possible endings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "20d", @"d. Predict possible endings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "20d", @"d. Predict possible endings.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 1, "Creating Texts", "20e", @"e. Relate ideas or events to one’s experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 2, "Creating Texts", "20e", @"e. Relate ideas or events to one’s experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Language", 3, "Creating Texts", "20e", @"e. Relate ideas or events to one’s experience.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "1", @"Count up to 100 (includes counting up or down from a given number and identifying a number that is 1 more or 1 less than a given number).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "2", @"Read and write numerals up to 100.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "3", @"Recognize and represent numbers up to 100 using a variety of concrete and pictorial models (e.g., number line, block or bar models, and numerals).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "4", @"Compare two numbers up to 20.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "5", @"Order numbers up to 20 from smallest to largest, and vice versa.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "6", @"Describe the position of objects using ordinal numbers: 1st, 2nd, 3rd, up to 10th.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "7", @"Compose and decompose numbers up to 10 using concrete materials.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "8", @"Illustrate addition of numbers with sums up to 20 using a variety of concrete and pictorial models and describes addition as “counting up,” and “putting together.”", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "9a", @"a. the sum of zero and any number is equal to the number", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "9b", @"b. changing the order of the addends does not change the sum", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "10", @"Solve problems (given orally or in pictures) involving addition with sums up to 20.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "11", @"Identify simple 2-dimensional shapes (triangle, rectangle, square) of different size and in different orientation.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "12", @"Compare and distinguish 2-dimensional shapes according to features such as sides and corners.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "13", @"Compose and decompose triangles, squares, and rectangles.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "14", @"Measure the length of an object and the distance between two objects using non-standard units.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "15", @"Compare lengths and distances using non-standard units.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 1, "General", "16", @"Solve problems involving lengths and distances using non-standard units.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "1", @"Order numbers up to 100 from smallest to largest, and vice versa.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "2", @"Counts by 2s, 5s and 10s up to 100.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "3a", @"a. the place value of a digit in a 2-digit number", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "4", @"b. the value of a digit", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "5", @"c. the digit of a number, given its place value", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "6", @"Decompose any 2-digit number into tens and ones.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "7", @"Add numbers by expressing addends as tens and ones (expanded form).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "8", @"Add numbers with sums up to 100 without regrouping, using a variety of concrete and pictorial models for: a. 2-digit and 1-digit numbers", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "8b", @"b. 2-digit and 2-digit numbers", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "9", @"Solve problems (given orally or in pictures) involving addition with sums up to 100 without regrouping.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "10", @"Illustrate subtraction involving numbers up to 20 using a variety of concrete and pictorial models and describes subtraction as “taking away.”", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "11", @"Find the missing number in addition or subtraction sentences involving numbers up to 20.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "12", @"Write an equivalent expression to a given addition or subtraction expression (e.g., 2+3 = 1+4; 10-5 = 6-1).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "13", @"Solve subtraction problems (given orally or in pictures) where both numbers are less than 20.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "14", @"Subtract numbers where both numbers are less than 100 using concrete and pictorial models, without regrouping: a. 2-digit minus 1-digit numbers", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "14b", @"b. 2-digit minus 2-digit numbers", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "15", @"Subtract numbers by expressing minuends and subtrahends as tens and ones (expanded form), without regrouping.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "16", @"Collect data in one variable through a simple interview.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "17", @"Present data in a pictograph without a scale.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "18", @"Interpret a pictograph without a scale.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 2, "General", "19", @"Organize data in a pictograph without a scale into a table.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "1", @"Determine the next term/s in a repeating pattern (patterns could use rhythmic properties, visual elements in the arts, …)", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "2", @"Create repeating patterns using objects, images, or numbers.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "3", @"Illustrate 1/2 and 1/4 as parts of a whole.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "4", @"Compare 1/2 and 1/4 using models.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "5", @"Count halves and quarters.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "6", @"Recognize coins (excluding centavo coins) and bills up to ₱100 and their notations.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "7", @"Determine the value of a number of bills and/or a number of coins (excluding centavo coins) up to ₱100.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "8", @"Compare different denominations of peso coins (excluding centavo coins) and bills up to ₱100.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "9", @"Solve 1-step problems (given orally or in pictures) involving addition of money where the sum is up to ₱100, or subtraction of money where both amounts are less than ₱100.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "10", @"Identify the position of objects moved in half turn or in quarter turn, in clockwise or in counter-clockwise direction, given an initial facing direction.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "11", @"Read and write time by the hour, half hour, and quarter hour using an analog clock.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "12", @"Give the days of the week and months of the year in the correct order.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "13", @"Determine the day and month of the year using a calendar.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Mathematics", 3, "General", "14", @"Solve problems involving time (hour, half hour, quarter hour, days in a week, and months in a year).", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 1, "Tiwala sa Sarili (Self-Confidence)", "1", @"Naipakikita ang tiwala sa sarili sa pamamagitan ng paggamit ng mga batayang impormasyon sa mga angkop na sitwasyon.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 1, "Pagiging Totoo (Sincerity)", "2", @"Naipapakita ang pagiging totoo sa pamamagitan ng mabuting pakikipag-ugnayan sa kapwa.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 1, "Tiyaga (Perseverance)", "3", @"Naipakikita ang pagiging matiyaga sa pamamagitan ng palagiang pagtatabi ng mga naipong pera sa alkansiya o mga gamit sa lagayan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 1, "Madasalin (Prayerful)", "4", @"Naipakikita ang pagiging madasalin sa pamamagitan ng wastong kilos at salita sa pananalangin", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 1, "Mapagpasalamat (Gratitude)", "5", @"Naipakikita ang pagiging mapagpasalamat sa pamamagitan ng pag-iingat ng mga yamang mula sa kapaligiran", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 1, "Magalang (Respectful)", "6", @"Naipakikita ang pagiging magalang sa pamamagitan ng mga angkop na kilos na nagbibigay-halaga sa mga karapatang tinatamasa bilang bata", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 1, "Kalinisan (Cleanliness)", "7", @"Naipakikita ang kalinisan sa pamamagitan ng palagiang pagsunod sa mga alituntunin sa paglilinis ng katawan ayon sa gabay ng pamilya, tagapangalaga, o nakatatanda", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Magalang (Respectful)", "1", @"Naipakikita ang pagiging magalang sa pamamagitan ng wastong pagtugon sa mensahe ng kapwa", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Responsable (Responsible)", "2", @"Naipakikita ang pagiging responsable sa pamamagitan ng pakikiisa sa mga munting gawain sa pamayanan ayon sa sariling kakayahan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Matulungin (Helpful)", "3", @"Naipakikita ang pagiging matulungin sa pamamagitan ng pagtulong sa mga gawain ng pamilya sa tahanan ayon sa kakayahan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Matulungin (Helpful)", "4", @"Naipakikita ang pagiging matulungin sa nakatatanda sa pamamagitan ng mga gawaing makatutulong at makapagbibigay-ginhawa sa kanila nang may pagsasaalang-alang sa ligtas na paraan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Madasalin (Prayerful)", "5", @"Nakapagsasanay sa pagiging madasalin sa pamamagitan ng pakikilahok sa pananalangin ng pamilya", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Kalinisan (Cleanliness)", "6", @"Naipakikita ang kalinisan sa pamamamagitan ng pakikibahagi sa mga gawain ng pangangalaga sa kapaligiran", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Masunurin (Obedient)", "7", @"Naipakikita ang pagiging masunurin sa pamamagitan ng pagtalima sa mga mabuting gawi ng pamilyang Pilipino", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Tiwala sa Sarili (Self-Confidence)", "8", @"Naipakikita ang tiwala sa sarili sa pamamagitan ng pagsasagawa ng mga gawain na nakabubuti sa sarili at sa kapwa bilang bahagi ng tagubilin ng pamilya", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 2, "Mapagbigay (Generosity)", "9", @"Naipakikita ang pagiging mapagbigay sa pamamagitan ng kusang-loob na pagbabahagi ng anumang mayroon siya", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Magalang (Respectful)", "1", @"Naipakikita ang pagiging magalang sa pamamagitan ng pagtalima sa mga tagubilin at alituntunin ng pook- dalanginan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Kalinisan (Cleanliness)", "2", @"Naipakikita ang kalinisan sa pamamagitan ng palagiang pagpapaalala sa kapwa-bata ng wastong pagpapanatili ng kaayusan at kalinisan ng kapaligiran", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Mapagmalasakit (Compassion)", "3", @"Naipakikita ang pagiging mapagbigay sa pamamagitan ng kusang-loob na pagbabahagi ng anumang mayroon siya", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Mapagbigay (Generosity)", "4", @"Naipakikita ang pagiging mapagbigay sa pamamagitan ng kusang-loob na pagbabahagi ng anumang mayroon siya", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Mabuting Mamamayan (Good Citizenship)", "5", @"Nakapagsasanay ng pagiging mabuting mamamayan sa pamamagitan ng kusang-loob na pagtulong sa pamilya sa mga gawaing pampamayanan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Magalang (Respectful)", "6", @"Nakapagsasanay sa pagiging magalang sa pamamagitan ng angkop na kilos sa iba’t ibang gawaing panrelihiyon o paniniwala sa pamayanan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Mapagmalasakit (Compassion)", "7", @"Naipakikita ang pagiging mapagmalasakit sa pamamagitan ng panghihikayat sa kapwa na makiisa sa mga simpleng gawain ng pangangalaga ng kapaligiran", ref displayOrder);
            Add(competencies, subjectId, learningArea, "GMRC", 3, "Pagmamahal sa Bayan (Love of Country)", "8", @"Naipakikita ang pagiging makabansa sa pamamagitan ng palagiang pagsunod sa mga panuntunan para sa mga sagisag ng bayan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 1, "General", "1a", @"a. Katangiang Pisikal", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 1, "General", "1b", @"b. Pangangailangan", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 1, "General", "2", @"Naipaliliwanag ang karapatan at tungkulin ng bawat bata.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 1, "General", "3", @"Napahahalagahan ang indibidwalidad ng bawat tao.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 2, "General", "1", @"Naipaliwanag ang konsepto ng pamilya batay sa bumubuo nito tulad ng two-parent, solo parents, extended family, at iba pa.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 2, "General", "2", @"Naipaliliwanag ang papel at tungkulin ng mga kasapi ng pamilya.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 2, "General", "3", @"Napahahalagahan ang papel at tungkulin ng mga kasapi ng pamilya.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 3, "General", "1", @"Nailalahad ang mga batayang impormasyon tulad ng pangalan, pinagmulan, laki at lawak, kinaroroonan, at kwento ng sariling paaralan.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 3, "General", "2", @"Naipaliliwanag ang tungkulin ng mga taong bumubuo sa paaralan tulad ng punong-guro, guro, doctor, nars, dyanitor, mag-aaral at iba pa.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 3, "General", "3", @"Natutukoy ang kahalagahan ng mga palatandaan at estruktura mula sa tahanan patungo sa paaralan.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 3, "General", "4", @"Napahahalagahan ang sariling paaralan bilang bahagi ng pamayanan.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 3, "General", "5", @"Natutukoy ang iba pang kasapi ng pamayanan na umaagapay sa pamilya at paaralan.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 3, "General", "6", @"Naipaliliwanag ang papel ng mga kasapi ng kinabibilangang pamayanan.", ref displayOrder);
            Add(competencies, subjectId, learningArea, "Makabansa", 3, "General", "7", @"Napahahalagahan ang papel ng mga kasapi ng kinabibilangang pamayanan.", ref displayOrder);
            return competencies;
        }

        private static void Add(List<PaceCompetency> target, int subjectId, string selectedArea, string requiredArea, int term, string domain, string code, string description, ref int displayOrder)
        {
            if (!selectedArea.Equals(requiredArea, StringComparison.OrdinalIgnoreCase)) return;
            target.Add(new PaceCompetency { SubjectId = subjectId, TermNumber = term, LearningArea = requiredArea, DomainName = domain, CompetencyCode = code, Description = description, DisplayOrder = displayOrder++, IsActive = true });
        }

        private static string NormalizeLearningArea(string subjectName)
        {
            string value = subjectName?.Trim().ToLowerInvariant() ?? string.Empty;
            if (value.Contains("reading") || value.Contains("literacy")) return "Reading & Literacy";
            if (value == "language" || value.Contains("language")) return "Language";
            if (value.Contains("math")) return "Mathematics";
            if (value == "gmrc" || value.Contains("good manners")) return "GMRC";
            if (value.Contains("makabansa")) return "Makabansa";
            return subjectName?.Trim() ?? string.Empty;
        }
    }
}
